# Generated by Django 4.2.16 on 2024-12-23 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_restaurantuser_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='item_category',
            field=models.CharField(choices=[('فست فود', 'فست فود'), ('نوشیدنی', 'نوشیدنی'), ('غذای ایرانی', 'غذای ایرانی'), ('دسر', 'دسر')], max_length=20),
        ),
    ]
