# Generated by Django 4.2.16 on 2024-12-23 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_menuitem_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='item_category',
            field=models.CharField(choices=[('fast_food', 'Fast Food'), ('beverage', 'Beverage'), ('traditional_food', 'Traditional Food'), ('dessert', 'Dessert')], max_length=20),
        ),
    ]
