# Generated by Django 4.2.16 on 2025-01-12 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_discountcode_discountusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='total_price_after_discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
