# Generated by Django 4.2.16 on 2025-01-13 02:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_customerorder_total_price_after_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountusage',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discount_usage', to=settings.AUTH_USER_MODEL),
        ),
    ]
